---
title: "522_conclusion"
output: pdf_document
date: "2024-12-15"
---

This report summarized how Monte Carlo simulation can be applied to pricing three types of options: European vanilla put options, Asian call options, and American vanilla put options. The results showed how to price complex options, especially when a closed formed solution was unavailable. Variance reduction techniques, such as the antithetic approach, the control variate approach, and the quasi-random sequence approach were used to improve the accuracy of the option price and the computational efficiency. In addition, the Longstaff-Schwartz method for American options and the Binomial Black-Scholes with Richardson Extrapolation method were used as benchmarks for early exercise strategies. This report showed how Monte Carlo simulations are able to precisely price complex options and investigated convergence speed and computational efficiency across the different methods.

In pricing the European vanilla put option with the following parameters, \( S_0 = K = 100, \, T = 0.5, \, r = 0.04, \, q = 0.02, \, \sigma = 0.2 \), the exact European put option price under Black-Scholes-Merton was calculated to be $5.0746. The standard Monte Carlo approach was the slowest at converging to within $0.01 of the exact price, with a sample size of around 256,000. The antithetic approach was the next fastest, converging to within $0.01 of the exact price with a sample size of around 64,000 (32,000 anithetic pairs). The Quasi-Monte-Carlo approach was the fastest, converging to within $0.01 of the exact price in around 4,000 samples.

In pricing the Asian call option under the Black-Scholes-Merton model, we applied the Monte Carlo simulation method combined with the moment matching technique to improve convergence and accuracy. The moment matching method adjusts the simulated standard normal samples to ensure they have a mean of zero and variance of one, aligning them more closely with the theoretical distribution. This adjustment reduces variance in the simulation, leading to faster and more stable convergence of the option price. The results demonstrated that the option price estimates stabilized as the sample size increased, converging to approximately $4.78. The standard error decreased at the theoretical rate of \( O(1/\sqrt{N}) \), confirming the efficiency of the Monte Carlo method. For smaller sample sizes, the estimates exhibited greater variability, reflected in wider confidence intervals. However, as the sample size increased to \( N = 256,000 \), the confidence interval narrowed significantly, and the standard error reduced to 0.009, achieving high precision. The computation time scaled linearly with the sample size, increasing from a negligible 0.008 seconds for \( N = 1000 \) to 2.4 seconds for \( N = 256,000 \). This trade-off between computational cost and accuracy highlights the importance of selecting an appropriate sample size for practical applications. The moment matching method proved effective in reducing variance and improving simulation efficiency, making it a reliable tool for pricing exotic options like Asian call options when closed-form solutions are unavailable.

In implementing the Least-Squares Monte Carlo (LSM) algorithm based on Longstaff-Schwartz to price an American Option on a dividend-paying stock, we included variance reduction techniques by using antithetic samples and excluding non-in-the-money paths when running the backward recursive least-squares regression. In terms of computational efficiency, replacing the the dataframe implementation with matrix implementation have proven to have significant improvement in pricing speed. Using the LSM model with $n=256000$ stock paths, $k=3$ regressors, and $m=80$ time steps, the option value converged to $2.2198$ with a standard error of under a cent. The Binomial Black-Scholes with Richardson Extrapolation (BSSR) model was also implemented and used as a benchmark in evaluating the LSM model's accuracy. The resulting BSSR price with 80 steps was $2.225939$, and with the LSM price of $2.2289$ using $n=64000$ stock paths, $k=3$ regressors, and $m=80$ time steps, an absolute error of around $0.003$ was achieved. Hence, in this specific experiment the LSM model with $64000$ stock paths represents an admissible trade off between speed and accuracy in pricing American options. 